export const genresSeed = [
  { name: 'Action' },
  { name: 'Adventure' },
  { name: 'Animation' },
  { name: 'Comedy' },
  { name: 'Crime' },
  { name: 'Documentary' },
  { name: 'Drama' },
  { name: 'Family' },
  { name: 'Fantasy' },
  { name: 'History' },
  { name: 'Horror' },
  { name: 'Music' },
  { name: 'Mystery' },
  { name: 'Romance' },
  { name: 'Science Fiction' },
  { name: 'TV Movie' },
  { name: 'Thriller' },
  { name: 'War' },
  { name: 'Western' },
];
